#if !canImport(ObjectiveC)
    import XCTest

    extension DangerSwiftCommitLintTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerSwiftCommitLintTests = [
            ("testDummy", testDummy),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(DangerSwiftCommitLintTests.__allTests__DangerSwiftCommitLintTests),
        ]
    }
#endif
