---
name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  danger:
    runs-on: ubuntu-latest
    name: "🚫 Run Danger"
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g danger
      - run: swift run danger-swift ci -c release --id "Lint"
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_SWIFT_GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    name: 🐧 Linux Test & Verify
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test-verify-action
        with:
          include-coverage: false

  macos:
    runs-on: macos-11
    name:  MacOS Test & Verify
    steps:
      - uses: actions/checkout@v2
      - name: Test & Coverage
        uses: ./.github/actions/test-verify-action
        with:
          include-coverage: true
          danger-token: ${{ secrets.DANGER_SWIFT_GITHUB_TOKEN }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
